behaviors:
  PlayerBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120    # PPO: 512 - 5120 ( large for continuous action, small for discrete)
      buffer_size: 51200  #  PPO: 2048 - 409600 ( larger = more stable updates)
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false    # can be helpful in cases with complex continuous control problems, but may be harmful with simpler discrete control problems.
      hidden_units: 512   # units in each layer (32 - 512 depending on complexity)
      num_layers: 3       # 1 - 3 depending on complexity
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # gail:               # Generative Adversarial Imitation Learning
      #   strength: 0.5     # How much it behaves like the demo 
      #   demo_path: ./demos/cheats/
    behavioral_cloning:   #? how is it different from gail ? Is it really worth using both ?
      strength: 0.2     
      demo_path: ./demos/cheats/
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 51200
