behaviors:
  PlayerBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
      gail:
        strength: 1.0
        demo_path: ./demos/trainable_demos
        network_settings:
          # normalize: true
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
    behavioral_cloning:
      strength: 1.0
      demo_path: ./demos/trainable_demos
      samples_per_update: 20480
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 10000
